dataset:
  class_distribution:
    test:
      0: 40
      1: 8
    train:
      0: 248
      1: 132
  test_size: 48
  train_size: 380
loss_function:
  parameters:
    alpha: 1.0
    gamma: 1
    pos_weight:
    - 1
    - 3
  type: FocalLoss
model:
  architecture: MultiBranchECGNet
  num_channels: 8
  num_classes: 2
  parameters:
    dropout_rate: 0.1
    learning_rate: 0.001
optimizer:
  parameters:
    lr: 0.001
    weight_decay: 1.0e-05
  type: Adam
