dataset:
  class_distribution:
    test:
      0: 40
      1: 8
    train:
      0: 248
      1: 132
  test_size: 48
  train_size: 380
loss_function:
  parameters:
    alpha: 2.0
    gamma: 3.0
    pos_weight:
    - 6
    - 1
  type: BCEWithLogitsLoss
model:
  architecture: MultiBranchECGNet
  num_channels: 8
  num_classes: 2
  parameters:
    dropout_rate: 0.5
    learning_rate: 0.001
optimizer:
  parameters:
    lr: 0.001
    weight_decay: 0.0001
  type: Adam
