augmentations:
  mask_prob: 0.3
  noise_level: 0.04
  shift_range: 0.2
dataset:
  class_distribution:
    test:
      0: 40
      1: 8
    train:
      0: 248
      1: 132
  test_size: 0
  train_size: 0
loss_function:
  parameters:
    alpha: 2.0
    gamma: 3.0
    pos_weight:
    - 1
    - 4
  type: FocalLoss
model:
  architecture: GroupedInceptionNet
  num_channels: 8
  num_classes: 2
  num_groups: 2
  parameters:
    dropout_rate: 0.1
    learning_rate: 0.001
optimizer:
  parameters:
    lr: 0.001
    weight_decay: 1.0e-05
  type: Adam
